src/Controller/PlantesApiController.php
src/Controller/PlantesController.php
src/Entity/Category.php
src/Entity/Plantes.php
src/Entity/Type.php
src/Form/PlantesType.php
src/Migrations/Version20200610095936.php
src/Repository/CategoryRepository.php
src/Repository/TypeRepository.php

Add tables Type and Category + ligth debug Json

Add tables Type and Category + ligth debug Json

---

src/Controller/DashboardController.php
src/Form/DashboardType.php
templates/dashboard/_delete_form.html.twig
templates/dashboard/_form.html.twig
templates/dashboard/edit.html.twig
templates/dashboard/index.html.twig
templates/dashboard/new.html.twig
templates/dashboard/show.html.twig

add CRUD for Dashboard

---

app/src/router/index.js
app/src/views/detail/Detail.vue
app/src/views/detail/detail.scss

Mise en page + responsive de la page

Carlyne page detail plante

---

src/Controller/PlantesApiController.php
src/Controller/PlantesController.php

API search OK

---

src/Controller/DashboardApiController.php
src/Controller/DashboardController.php
src/Controller/PlantesApiController.php
src/Controller/UserApiController.php
src/Repository/DashboardRepository.php
src/Security/FormAuthenticator.php

find all dash with API, more verif on search plants

find all dash with API, more verif on search plants

---

src/Controller/ArrosedController.php
src/Entity/Plantes.php
src/Repository/ArrosedRepository.php

add ArrosedController for change the date of arrosage

add ArrosedController for change the date of arrosage

---

src/Controller/ArrosedController.php
src/Controller/DashboardApiController.php
src/Controller/PlantesApiController.php
src/Repository/DashboardRepository.php

add function for find 2 biggers dashboard and all relations

add function for find 2 biggers dashboard and all relations

---

app/src/main.js
app/src/router/index.js
app/src/store/index.js
app/src/views/dashboard/Dashboard.vue
app/src/views/home/Home.vue
package-lock.json
package.json

Ne pas oublier de faire `npm install `!

user disponible dans un store global, on peut afficher son dashboard

---

src/Controller/DashboardApiController.php
src/Controller/DashboardController.php
src/Controller/PlantesApiController.php

correction faute de frappe

---

app/src/router/index.js
app/src/views/authentification/Login.vue
app/src/views/authentification/Register.vue
src/Controller/RegistrationController.php
templates/registration/api_register.html.twig

Ajout formulaire page authentification/inscription + ajout d'une route api/register et son template associé dans Symfony.

ajout page authentification inscription

---

src/Controller/DashboardController.php
src/Security/EmailVerifier.php

commit light modif

---

app/src/components/Filtrage.vue
app/src/components/plant-card/PlantCard.vue
app/src/router/index.js
app/src/views/about/about.scss
app/src/views/catalogue/Catalogue.vue
app/src/views/dashboard/Dashboard.vue
app/src/views/detail/detail.scss
src/Controller/PlantesApiController.php

Changement des conditions pour la route plante/search dans Api Controller

correction bug de filtrage : filtrage ok

---

src/Controller/ArrosedController.php
src/Controller/PlantesApiController.php

add isArrosed for plante of Dashboard

add isArrosed for plante of Dashboard

---

src/Form/RegistrationFormType.php
templates/base.html.twig
templates/registration/register.html.twig

light modif (fix)

---

app/src/components/plant-card/PlantCard.vue
app/src/components/plant-card/plant-card.scss
templates/base.html.twig

add hover on PlanCard

---

app/src/components/Navbar.vue
app/src/components/plant-card/PlantCard.vue
src/Controller/DashboardController.php
templates/registration/register.html.twig

navbar OK, light modif

---

app/src/components/Navbar.vue
src/Entity/Dashboard.php

add username in 2 biggers dashboards

---

app/src/components/plant-card/PlantCard.vue
app/src/components/plant-card/plant-card.scss

modif PlantCard

---

src/Controller/DashboardApiController.php
src/Controller/SecurityController.php
src/Controller/UserApiController.php
src/Entity/Arrosed.php
src/Entity/Carve.php
src/Entity/Category.php
src/Entity/Cutting.php
src/Entity/Dashboard.php
src/Entity/Difficulty.php
src/Entity/Flowering.php
src/Entity/Plantes.php
src/Entity/Potting.php
src/Entity/Sunshine.php
src/Entity/Type.php
src/Entity/User.php
src/Entity/Watering.php
templates/base.html.twig
templates/security/login.html.twig

change Groups of Json

---

src/Controller/SecurityController.php
src/Security/FormAuthenticator.php
templates/base.html.twig

test modif security

---

app/src/components/plant-card/PlantCardHome.vue

change link on example dashboards

---

app/src/views/authentification/Login.vue
app/src/views/authentification/Register.vue
src/Controller/RegistrationController.php
src/Controller/SecurityController.php

message for cnx error OK

---

src/Controller/AppController.php
src/Controller/ArrosedController.php
src/Controller/DashboardApiController.php
src/Controller/DashboardController.php
src/Controller/PlantesApiController.php
src/Controller/RegistrationController.php
src/Controller/SecurityController.php
src/Controller/UserApiController.php
src/Repository/ArrosedRepository.php
src/Repository/PlantesRepository.php

add some comments

---

app/src/components/plant-card/PlantCard.vue
app/src/components/plant-card/PlantCardHome.vue
app/src/components/plant-card/plant-card.scss

light modif on hover

---

app/src/components/plant-card/PlantCard.vue

last commit

---

app/src/views/authentification/Register.vue
templates/registration/register.html.twig
templates/security/login.html.twig

add text password on register
